### ISSUE TITLE
如何进入后台?

### ISSUE THREAD

**Issue by Lucacaa** [SomeBottle/-O-#2]
搭建好了,发了篇文章之后发现不会进入后台 尴尬

**Comment by SomeBottle** [comment]
请问你是进行初始化了吗，希望能提供几张截图:D




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SomeBottle/-O-"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 晚上8:54
收件人:&nbsp;"SomeBottle/-O-"<-O-@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[SomeBottle/-O-] 如何进入后台? (#2)





 
搭建好了,发了篇文章之后发现不会进入后台 尴尬

**Comment by SomeBottle** [comment]
长时间无互动
