### ISSUE TITLE
搭建的时候初始化失败

### ISSUE THREAD

**Issue by Moebest** [SomeBottle/-O-#3]
Moebest.github.io 可以看看
![image](https://user-images.githubusercontent.com/65937132/90645902-1af61600-e269-11ea-98e4-38672cbecd97.png)

**Comment by Moebest** [comment]
我现在搭建直接不能初始化了咋整emm

**Comment by SomeBottle** [comment]
久等了，我刚才锻炼去了...
这个问题是最近才出现的，原因是无法连接上github的api，这个是和某墙是有关的.
可以尝试一下hosts或者科学上网工具.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SomeBottle/-O-"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 晚上10:13
收件人:&nbsp;"SomeBottle/-O-"<-O-@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [SomeBottle/-O-] 搭建的时候初始化失败 (#3)





 
我现在搭建直接不能初始化了咋整emm
