### ISSUE TITLE
原谅我wiki部署看不懂。。。。还有请问-O-怎么弄评论系统？

### ISSUE THREAD

**Issue by JesseJeson** [SomeBottle/-O-#4]

**Comment by SomeBottle** [comment]
你先跟着wiki一步一步来，到哪一步卡住了我解释一下
评论框你要修改模板里的comment.html
接入第三方评论框

**Comment by JesseJeson** [comment]
就是这个博客不是要用两个仓库，一个前台仓库，一个后台仓库，我搞不清部署中的每一个步骤是在前台仓库执行还是在后台仓库执行

**Comment by JesseJeson** [comment]
(>﹏<)

**Comment by SomeBottle** [comment]
博客前台需要在github创建一个仓库，然后-O-仓库的主体内容你可以随便找个网站服务器塞上去，相当于后台
例如我博客的仓库是```blog```，绑定了域名233.moe，我把 https://github.com/SomeBottle/-O- 仓库下的内容放在```blog/admin```目录里。
然后访问 http://233.moe/admin/ 就可以进入后台开始部署了

**Comment by JesseJeson** [comment]
也就是实际上一个仓库就可以实现-O-的部署？

**Comment by SomeBottle** [comment]
是的
