### ISSUE TITLE
请问能给一个改好了的comment.html示例吗，我不太会改，谢谢了

### ISSUE THREAD

**Issue by JesseJeson** [SomeBottle/-O-#6]

**Comment by BottleSome** [comment]
其实你去我博客看源码就知道了，这里用的是第三方评论框。我博客用的自建的评论服务
 https://bottle.moe/comment.otp.html

**Comment by BottleSome** [comment]
重点在于你要先了解第三方评论框是什么样的一个服务～是怎么部署的
有一个依赖github的第三方评论框你可以看一下：
https://utteranc.es/

**Comment by BottleSome** [comment]
如果你看了README或者wiki应该能知道这个页面源码里的{[pid]}是文章唯一id

**Comment by JesseJeson** [comment]
请问怎么在文章中插入评论框？还有请问怎么创建搜索界面？谢谢谢谢！

**Comment by BottleSome** [comment]
请认真阅读wiki和README
文章中的评论框就是改comment.otp.html
我的博客就是示例，希望你能活用查看源代码功能，搜索页面是要你自己创建页面写javascript的，怎么创建页面其实README里也写了
不是所有东西口头能讲清楚

**Comment by JesseJeson** [comment]
好的，谢谢
