### ISSUE TITLE
请问出现这种情况是怎么回事？

### ISSUE THREAD

**Issue by histcat** [SomeBottle/-O-#7]
![image](https://user-images.githubusercontent.com/83163975/126597236-52595c93-deb9-44d2-8006-4d89ede3ceeb.png)
histcatnote.hd.lc/comment.otp.html有显示
![image](https://user-images.githubusercontent.com/83163975/126597308-234c4374-8648-4f2c-9d8b-c923743805fc.png)
这是这个界面的代码
但是文章界面没显示出评论来
![image](https://user-images.githubusercontent.com/83163975/126597385-3812751a-6e9c-49df-a5ed-0bc6aaadc40e.png)
请问是哪里出了差错？

**Comment by SomeBottle** [comment]
这个地方是-O-的问题，处理之后丢失了script原有属性，而这个评论框依赖于script属性
刚刚我已经修复了这个问题
只需要替换你现在博客仓库的：
https://github.com/JesseJeson/JesseJeson.github.io/blob/main/main.js  
为
https://github.com/SomeBottle/-O-/blob/master/template/main.js  
即可解决问题

**Comment by JesseJeson** [comment]
谢谢！（发issues的时候忘记切大号了）
