### ISSUE TITLE
还有一个问题，不知道是bug还是我没配置好

### ISSUE THREAD

**Issue by JesseJeson** [SomeBottle/-O-#8]
https://user-images.githubusercontent.com/55904993/126751914-2912b0c6-6563-4eac-8725-4b44600be6bb.mp4

如视频，评论到了别的界面依然存在，即使到了别的文章也会覆盖了那个文章的评论框，刷新后就好了

**Comment by JesseJeson** [comment]
视频有点卡

**Comment by SomeBottle** [comment]
明显是评论框自己的问题，我也搞不明白这个作者为什么要让评论框架元素创建在最外层导致和页面脱节
只能说用不了这个评论框了
我只能推荐这个项目了：https://github.com/gitalk/gitalk/blob/master/readme-cn.md

**Comment by JesseJeson** [comment]
好的，谢谢！
