### ISSUE TITLE
初始化博客一直转圈

### ISSUE THREAD

**Issue by JesseJeson** [SomeBottle/-O-#9]
![aaa](https://user-images.githubusercontent.com/55904993/147873138-638ffd53-2fa4-4979-b7eb-bbb851d3adaf.PNG)

**Comment by SomeBottle** [comment]
请F12打开控制台进行截图，光此画面我无法判定任何问题
以后无论在哪个前端项目发issue，请记得带上控制台截图。

**Comment by SomeBottle** [comment]
初步猜测是```api.github.com```无法访问
由于众所周知原因，Github在国内访问情况不佳

**Comment by JesseJeson** [comment]
哦哦，解决了，谢谢！
